[package]
authors = ["Benno Fünfstück <benno.fuenfstueck@gmail.com>"]
name = "nix-index"
version = "0.1.1"

[[bin]]
doc = false
name = "nix-index"

[[bin]]
name = "nix-locate"

[dependencies]
ansi_term = "0.10.2"
bincode = "0.9.2"
brotli2 = "0.3.2"
byteorder = "1.2.1"
clap = "2.30.0"
error-chain = "0.11.0"
futures = "0.1.17"
grep = "0.2.0"
hyper = "0.11.12"
isatty = "0.1.6"
memchr = "2.0.2"
ordermap = "0.3.4"
regex = "0.2.5"
regex-syntax = "0.4.2"
separator = "0.3.1"
serde = "1.0.27"
serde_bytes = "0.10.3"
serde_derive = "1.0.27"
serde_json = "1.0.9"
stderr = "0.8.0"
tokio-core = "0.1.12"
tokio-retry = "0.1.1"
tokio-timer = "0.1.2"
void = "1.0.2"
xdg = "2.1.0"
xml-rs = "0.7.0"
xz2 = "0.1.4"
zstd = "0.4.17+zstd.1.3.3"

[[example]]
name = "nix-index-debug"

[profile]

[profile.release]
debug = true
